### ISSUE TITLE
Lists aren't rendered "pretty"

### ISSUE THREAD

**Issue by chrillefkr** [jorsn/flakegen#1]
This example `flake.in.nix`

```nix
{
  description = "Example test for lists in nixConfig";

  nixConfig = {
    substituters = [
      "https://cache.nixos.org/"
    ];
    trusted-public-keys = [
      "cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY="
    ];
  };
}
```

when run through `genflake` generates

```nix
# Do not modify! This file is generated.

{
  description = "Example test for lists in nixConfig";
  inputs.flakegen.url = "github:jorsn/flakegen";
  nixConfig = {
    substituters = https://cache.nixos.org/;
    trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=;
  };
  outputs = inputs: inputs.flakegen ./. ((import ./flake.in.nix).outputs inputs);
}
```

Notice that the `nixConfig.substituters` and `nixConfig.trusted-public-keys` are originally lists, but rendered without brackets (`[]`) and without quotes for the strings. I think it all breaks if you'd have a list with anything that can't be `toString`-ified out-of-the-box, e.g. list with attrsets (`[ { } ]`).

**Comment by jorsn** [comment]
Thanks a lot! I completely forgot to care about rendering lists.

Sidenote: Are lists in nixConfig.* values allowed/effective, or must they be strings? I couldn't find documentation about it. However, this is not the issue here – we should render a list as a list, and the user can, e.g., decide to set `nixConfig = mapAttrs (n: v: toString v)`.

**Comment by chrillefkr** [comment]
No problem! Thanks for this project, I really like it so far. I prefer this method over patching `nix` for using [Combined Manager](https://github.com/FlafyDev/combined-manager) (also an awesome project).

The `nixConfig` attribute is explained in the manual [here](https://nixos.org/manual/nix/stable/command-ref/new-cli/nix3-flake#flake-format) (or `man nix3-flake`) under section flake-format:

> `nixConfig`: a set of `nix.conf` options to be set when evaluating any
part of a flake. In the interests of security, only a small set of set
of options is allowed to be set without confirmation so long as
[`accept-flake-config`](/manual/nix/stable/command-ref/conf-file#conf-accept-flake-config)
is not enabled in the global configuration:
> 
> - [`bash-prompt`](/manual/nix/stable/command-ref/conf-file#conf-bash-prompt)
> - [`bash-prompt-prefix`](/manual/nix/stable/command-ref/conf-file#conf-bash-prompt-prefix)
> - [`bash-prompt-suffix`](/manual/nix/stable/command-ref/conf-file#conf-bash-prompt-suffix)
> - [`flake-registry`](/manual/nix/stable/command-ref/conf-file#conf-flake-registry)
> - [`commit-lockfile-summary`](/manual/nix/stable/command-ref/conf-file#conf-commit-lockfile-summary)

And `nix.conf` is documented [here](https://nixos.org/manual/nix/stable/command-ref/conf-file.html#conf-substituters) (or `man nix.conf`). Though I'm not sure it's stated anywhere, `nix.conf` doesn't want brackets nor quotes for its values, but nixConfig does. This is evident in NixOS's [`nix.settings`](https://github.com/NixOS/nixpkgs/blob/428544ae95eec077c7f823b422afae5f174dee4b/nixos/modules/config/nix.nix#L82C1-L128).

**Comment by jorsn** [comment]
Thanks for the compliments and the link to combined-manager! I hope this is useful.

In [`nix.settings`](https://github.com/NixOS/nixpkgs/blob/428544ae95eec077c7f823b422afae5f174dee4b/nixos/modules/config/nix.nix#L87), they print lists with `toString`,
~~~nix
        else if isList v then toString v
~~~
which converts `[ "a" "b" "c" ]` to `"a b c"`. It seems that `nixConfig` is also converted with `toString` or so, since the line
~~~nix
  nixConfig.extra-substituters = [ "https://jorsn.cachix.org" "https://nix-community.cachix.org" ];
~~~
results in
~~~
$ nix run .#genflake
do you want to allow configuration setting 'extra-substituters' to be set to 'https://jorsn.cachix.org https://nix-community.cachix.org' (y/N)?
~~~
