### ISSUE TITLE
Can't add an inputs to `inputs` and `outputs` at the same time.

### ISSUE THREAD

**Issue by FlafyDev** [jorsn/flakegen#3]
If you use the template and add another input, `nixpkgs2`, to `flake.in.nix`:

```nix
{

  description = "The real nix file";

  inputs = let
    dep = url: { inherit url; inputs.nixpkgs.follows = "nixpkgs"; };
  in {
    # flakegen needn't be declared, here. It is automatically added when
    # generating flake.nix.
    nixlib.url = "github:nix-community/nixpkgs.lib";
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    nix-darwin = (dep "github:LnL7/nix-darwin");
    home-manager = (dep "github:nix-community/home-manager");

    nixpkgs2.url = "github:NixOS/nixpkgs/nixos-unstable";
  };

  outputs = { nixpkgs, nixpkgs2, ... }@inputs: {
    # you can write the outputs as usual. They will be called from the generated
    # flake.nix.
    packages.x86_64-linux.hello = nixpkgs2.legacyPackages.x86_64-linux.hello;
  };

}
```

you get an error:
```
❯ nix run .#genflake flake.nix
warning: updating lock file '/home/flafy/repos/random/flakegentest/flake.lock':
• Added input 'home-manager':
    'github:nix-community/home-manager/4d53427bce7bf3d17e699252fd84dc7468afc46e' (2024-02-01)
• Added input 'home-manager/nixpkgs':
    follows 'nixpkgs'
• Added input 'nix-darwin':
    'github:LnL7/nix-darwin/bdbae6ecff8fcc322bf6b9053c0b984912378af7' (2024-02-02)
• Added input 'nix-darwin/nixpkgs':
    follows 'nixpkgs'
• Added input 'nixlib':
    'github:nix-community/nixpkgs.lib/4833b4eb30dfe3abad5a21775bc5460322c8d337' (2024-01-28)
• Added input 'nixpkgs':
    'github:NixOS/nixpkgs/b8b232ae7b8b144397fdb12d20f592e5e7c1a64d' (2024-01-31)
error:
       … in the left operand of the update (//) operator

         at «string»:56:13:

           55|             # This is shadowed in the next //
           56|             // sourceInfo
             |             ^
           57|             // {

       … from call site

         at /nix/store/79anbyzvswp8r5m9ql2qyr803vfiy843-source/flake.nix:18:21:

           17|   };
           18|   outputs = inputs: inputs.flakegen ./. ((import ./flake.in.nix).outputs inputs);
             |                     ^
           19| }

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: function 'outputs' called without required argument 'nixpkgs2'

       at /nix/store/79anbyzvswp8r5m9ql2qyr803vfiy843-source/flake.in.nix:18:13:

           17|
           18|   outputs = { nixpkgs, nixpkgs2, ... }@inputs: {
             |             ^
           19|     # you can write the outputs as usual. They will be called from the generated
```

As written in the README, this fixes it:
```
rm flake.nix
nix flake init -t github:jorsn/flakegen
nix run .#genflake flake.nix
```

but I prefer not to call `nix flake init` every time when I want to update my inputs

**Comment by jorsn** [comment]
Thanks for reporting! You shouldn't have to init every time.
I am trying to come up with a solution, but it isn't straight-forward.

Possible workarounds (that I tested) are
1. Regenerate the file after adding inputs and before using them in the outputs.
2. Write `flake.in.nix` like `outputs = { nixpkgs ? {}, nixpgks2 ? {}, ... }: { ... };`.
3. Write `flake.in.nix` like `outputs = inputs: with inputs; { ... };`.

The problem is that as long as the inputs of `flake.nix` are not updated, your outputs cannot be called, since *required* function arguments are missing. I might be wrong, but to me it does not seem that *function arguments* can be lazily matched.
Workarounds (2.) and (3.) circumvent the check for declared inputs, and thus there can be an evaluation error in the outputs if
e.g. you try to evaluate an argument referencing the missing `nixpkgs2`, i.e., until you regenerate the `flake.nix`.

Hence, this sacrifices a bit of safety: You can only check for this error by fully evaluating the whole outputs function. **Edit:** Is this done by `nix flake show`?

Do you have any other possible workaround/solution in mind? Are the workarounds satisfactory for you, if they are documented in the readme?

**Comment by jorsn** [comment]
One could also leave `flake.in.nix` unmodified and instead put the following in `flake.nix`.

Workaround 4:
~~~nix
  outputs = inputs: let
    template = import ./flake.in.nix;
    in inputs.flakegen ./. (template.outputs (template.inputs // inputs));
~~~

This would have a bit of safety: Only inputs which are declared in `flake.in.nix` can be used, so the remaining source of error is not to regenerate `flake.nix` before trying to use the flake outputs.

Something similar could also be abstracted into `flakegen`. Or it could be documented as a way of writing `flake.in.nix`, to leave the choice to the user.

What do you think?
